### ISSUE TITLE
Can the spec explain more on how $ref is intended to work

### ISSUE THREAD

**Issue by bbakerman** [graphql-cats/graphql-cats#13]
There is data like this

```
        data:
          a: Apple
          b: Banana
          c: Cookie
          c: Cookie
          d: Donut
          e: Egg
          f: Fish
          deep: {$ref: deepData}
          promise: {$ref: data}
        deepData:
          a: Already Been Done
          b: Boring
          c:
            - "Contrived"
            - null
            - Confusing
          deeper:
            - {$ref: data}
            - null
            - {$ref: data}
```

The $ref is used as a pointer to other parts.  I am not sure exactly the scope of this and how one would implement self referencing data
