### ISSUE TITLE
The ParserTests have invalid syntax named as valid

### ISSUE THREAD

**Issue by bbakerman** [graphql-cats/graphql-cats#15]
In the two tests we have

```
- name: Simple type inheriting interface
    given:
      query: type Hello implements World { }
    when:
      parse:
    then:
      passes:

  - name: Simple type inheriting multiple interfaces
    given:
      query: type Hello implements Wo, rld { }
    when:
      parse:
    then:
      passes:
```

What I think is invalid is the empty field declaration at the end of the type eg the `{}` bit

I read the the graphql spec as

https://github.com/facebook/graphql/blob/master/spec/Section%203%20--%20Type%20System.md

```
ObjectTypeDefinition : Description? type Name ImplementsInterfaces? Directives[Const]? FieldsDefinition?

ImplementsInterfaces :

implements &? NamedType
ImplementsInterfaces & NamedType
FieldsDefinition : { FieldDefinition+ }

FieldDefinition : Description? Name ArgumentsDefinition? : Type Directives[Const]?
```

My reading of that is that an object type may have zero `FieldsDefinition` but if it it does then it must have 1 or more `FieldDefinition`

But perhaps I am wrong.  Does `FieldDefinition+` read as `zero or more` or is it `one or more`?

The grammar notes here seem to say `one or more`

https://github.com/facebook/graphql/blob/master/spec/Appendix%20A%20--%20Notation%20Conventions.md
