### ISSUE TITLE
Question about test in execution/UnionInterface.yaml scenario

### ISSUE THREAD

**Issue by cjoudrey** [graphql-cats/graphql-cats#26]
I'm working on getting `graphql-cats` to pass on `graphql-ruby` and stumbled on this test:

```yaml
  - name: executes using union types
    given:
      query: |
        {
          __typename
          name
          pets {
            __typename
            name
            barks
            meows
          }
        }
    when:
      execute:
        validate-query: false
        test-value: bob
    then:
      data: 
        __typename: "Person"
        name: "Bob"
        pets:
          - __typename: "Cat"
            name: "Garfield"
            meows: false
          - __typename: "Dog"
            name: "Odie"
            barks: true
```

In theory this isn't a valid query because [one cannot select fields directly off a union type](http://facebook.github.io/graphql/June2018/#sec-Field-Selections-on-Objects-Interfaces-and-Unions-Types).

I'm assuming by passing `validate-query: false`, implementations are supposed to ignore this rule and allow selections, but why would we want to do this? More generally, what's the purpose of `validate-query: false`? Does the spec define how implementations should execute a query when validation is bypassed? If not, can we remove `validate-query` as an option?

Instead of the above test, what are your thoughts on this one:

```yaml
  - name: executes using union types
    given:
      query: |
        {
          __typename
          name
          pets {
            __typename
            name
            ... on Dog {
              barks
            }
            ... on Cat {
              meows
            }
          }
        }
    when:
      execute:
        test-value: bob
    then:
      data: 
        __typename: "Person"
        name: "Bob"
        pets:
          - __typename: "Cat"
            name: "Garfield"
            meows: false
          - __typename: "Dog"
            name: "Odie"
            barks: true
```

I feel like the above test is more close to reality and doesn't make any assumptions on how implementations should behave when query validation is disabled.

**Edit:** Just found this interesting snippet from the spec:

> An invalid request is still technically executable, and will always produce a stable result as defined by the algorithms in the Execution section, however that result may be ambiguous, surprising, or unexpected relative to a request containing validation errors, so execution should only occur for valid requests.
